name: Publish Snapshots

on:
  push:
    branches:
      - main

jobs:
  # Run Gradle Wrapper Validation to verify the wrapper's checksum
  gradle_validation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: gradle_validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
          cache: 'gradle'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish Snapshots
        run: >-
          ./gradlew --no-daemon publishToSonatype -x test
          -Psigning.gnupg.keyName=$GPG_KEY_ID
          -Psigning.gnupg.passphrase="$GPG_PASSPHRASE"
          -PsonatypeUsername="$OSSRH_USERNAME"
          -PsonatypePassword="$OSSRH_TOKEN"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

